---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpatroller
  namespace: penpatroller
spec:
  selector:
    matchLabels:
      app: penpatroller
  replicas: 1
  template:
    metadata:
      labels:
        app: penpatroller
    spec:
      containers:
        - image: 705874861180.dkr.ecr.us-east-1.amazonaws.com/penpatroller:latest
          name: penpatroller
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 128Mi
              cpu: 256m
