apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamashaver
  namespace: llama-shaver
spec:
  selector:
    matchLabels:
      app: llamashaver
  replicas: 1
  template:
    metadata:
      labels:
        app: llamashaver
    spec:
      containers:
        - image: 705874861180.dkr.ecr.us-east-1.amazonaws.com/llama-shaver:latest
          name: llamashaver
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 128Mi
              cpu: 256m
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SQS_QUEUE_URL_SOURCE
              value: "https://sqs.us-east-1.amazonaws.com/705874861180/LlamaConveyorBeltSource"
            - name: SQS_QUEUE_URL_DESTINATION
              value: "https://sqs.us-east-1.amazonaws.com/705874861180/LlamaConveyorBeltDestination"
            - name: "TEAM_ID"
              value: "277459b8-77af"
            - name: "AWS_REGION"
              value: "us-east-1"

---
apiVersion: v1
kind: Service
metadata:
  name: llamashaver-service
  namespace: llama-shaver
spec:
  selector:
    app: llama-shaver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer


